version: '3.8'

services:
  price_it_app:
    depends_on:
      - mongo
      - redis
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:  
      - ${DOCKER_SERVER_PORT}:${LOCAL_SERVER_PORT}
    volumes:
      - .:/usr/src/price_it_app
      - /usr/src/app/node_modules
    links:
      - redis 

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - mongo:/data/mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

  redis:
    image: redis
    container_name: redis
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    env_file: ./.env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data/redis
    restart: unless-stopped


volumes:
  mongo:
  redis:

